/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author glei-
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    /**
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public MenuPrincipal() {
        initComponents();
        this.setExtendedState(MenuPrincipal.MAXIMIZED_BOTH);
        ImageIcon icone = new ImageIcon("./image/default.png");
        setIconImage(icone.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mEstoque = new javax.swing.JMenuItem();
        mOs = new javax.swing.JMenuItem();
        mVendas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mrEstoque = new javax.swing.JMenuItem();
        mrFuncionario = new javax.swing.JMenuItem();
        mrVendas = new javax.swing.JMenuItem();
        jMAdmin = new javax.swing.JMenu();
        maFuncionario = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Principal (SysTec)");

        jPanel1.setBackground(java.awt.Color.lightGray);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Document.png"))); // NOI18N
        jMenu1.setText("Cadastros");

        mEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1475643978_20.png"))); // NOI18N
        mEstoque.setText("Estoque");
        jMenu1.add(mEstoque);

        mOs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1475644115_wrench.png"))); // NOI18N
        mOs.setText("Ordem de Serviço");
        mOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOsActionPerformed(evt);
            }
        });
        jMenu1.add(mOs);

        mVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sales.png"))); // NOI18N
        mVendas.setText("Iniciar Vendas");
        jMenu1.add(mVendas);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/notepade.png"))); // NOI18N
        jMenu2.setText("Relatorios");

        mrEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1475643978_20.png"))); // NOI18N
        mrEstoque.setText("Estoque");
        jMenu2.add(mrEstoque);

        mrFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/free17.png"))); // NOI18N
        mrFuncionario.setText("Funcionarios");
        jMenu2.add(mrFuncionario);

        mrVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sales.png"))); // NOI18N
        mrVendas.setText("Vendas");
        jMenu2.add(mrVendas);

        jMenuBar1.add(jMenu2);

        jMAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/147_male.png"))); // NOI18N
        jMAdmin.setText("Adminitrador");

        maFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/free17.png"))); // NOI18N
        maFuncionario.setText("Funcionarios");
        maFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maFuncionarioActionPerformed(evt);
            }
        });
        jMAdmin.add(maFuncionario);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/147_male.png"))); // NOI18N
        jMenuItem1.setText("Admin");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMAdmin.add(jMenuItem1);

        jMenuItem2.setText("Garantia");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMAdmin.add(jMenuItem2);

        jMenuBar1.add(jMAdmin);

        mSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit-to-app (2).png"))); // NOI18N
        mSair.setText("Sair");
        mSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(mSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSairMouseClicked
        if (JOptionPane.showConfirmDialog(null, "Deseja Fechar?", "ATENÇÂO ", JOptionPane.YES_NO_OPTION) == 0) {

            System.exit(0);
        }
    }//GEN-LAST:event_mSairMouseClicked

    private void maFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maFuncionarioActionPerformed
       Autenticacao.main(null);
       
    }//GEN-LAST:event_maFuncionarioActionPerformed

    private void mOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mOsActionPerformed
        CadOs os = new CadOs();
        os.setVisible(true);
    }//GEN-LAST:event_mOsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       Autenticacao2.main(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      Autenticacao3.main(null);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMAdmin;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mEstoque;
    private javax.swing.JMenuItem mOs;
    private javax.swing.JMenu mSair;
    private javax.swing.JMenuItem mVendas;
    private javax.swing.JMenuItem maFuncionario;
    private javax.swing.JMenuItem mrEstoque;
    private javax.swing.JMenuItem mrFuncionario;
    private javax.swing.JMenuItem mrVendas;
    // End of variables declaration//GEN-END:variables
}
